name: offline_sync
publish_to: none
environment:
  sdk: ^3.12.0
workspace:
  - packages/offline_sync_ui
  - packages/offline_sync_core
  - packages/offline_sync_flutter
dev_dependencies:
  melos: ^7.8.1
